image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

before_script:
  - python --version
  - pip install hatch --quiet

stages:
  - build
  - test
  - publish

build:
  stage: build
  script: hatch build
  artifacts:
    paths:
      - dist
    expire_in: 1 week

check types:
  stage: test
  script: hatch run types:check

publish:
  stage: publish
  dependencies:
    - build
  script: hatch publish
  rules:
    - if: $CI_COMMIT_BRANCH == "main"